2019-01-21T11:20:04|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\nidaqmx_test\ni_app.py", line 37, in <module>
    app = NI_App(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_app.py", line 21, in setup
    self.add_hardware(NI_DO_hw(self))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 80, in __init__
    self.setup()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_do_hardware.py", line 20, in setup
    print(device.name + ' : ' + device.terminals)
TypeError: can only concatenate str (not "list") to str

